{{- if and .Values.networkPolicies.enabled .Values.postgresql.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "matrix-sliding-sync.fullname" . }}-synapse-postgresql
  labels:
{{ include "matrix-sliding-sync.labels" . | indent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "postgresql.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: {{ include "matrix-sliding-sync.name" . }}-synapse
          app.kubernetes.io/instance: {{ .Release.Name }}
    ports:
      - port: tcp-postgresql
        protocol: TCP
{{- end }}
